import { Footer, Layout, Navbar } from 'nextra-theme-docs'
import { Head } from 'nextra/components'
import { getPageMap } from 'nextra/page-map'
import 'nextra-theme-docs/style.css'

export const metadata = {
  title: {
    default: 'No MDX - One YAML OpenAPI',
    template: '%s – Docs'
  },
  description: 'Documentation site'
}

const navbar = (
  <Navbar
    logo={<span style={{ fontWeight: 700 }}>No MDX - One YAML OpenAPI</span>}
    projectLink="https://github.com/Jolli-sample-repos/sample-one-yaml-no-mdx"
  />
)

const footer = <Footer>No MDX - One YAML OpenAPI · Generated by Jolli</Footer>

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" dir="ltr" suppressHydrationWarning>
      <Head>
        <style>{`:root { --nextra-primary-hue: 212deg; }`}</style>
        
      </Head>
      <body>
        <Layout
          navbar={navbar}
          footer={footer}
          pageMap={await getPageMap()}
          editLink={null}
          feedback={{ content: null }}
          toc={{ title: 'On This Page' }}
          darkMode={true}
          nextThemes={{ defaultTheme: 'system' }}
        >
          {children}
        </Layout>
      </body>
    </html>
  )
}
